DROP USER JMJP CASCADE;
CREATE USER JMJP
IDENTIFIED BY JMJP;
GRANT CONNECT,RESOURCE TO JMJP;
GRANT DBA TO JMJP;
CONN JMJP/JMJP;

//USER TABLE//

CREATE TABLE USERS (
USER_NAME VARCHAR2(20) PRIMARY KEY,
PASSWORD VARCHAR(10) UNIQUE);

//PRODUCT TABLE//

CREATE TABLE PRODUCT(
PRODUCT_ID VARCHAR2(10) PRIMARY KEY,
PRODUCT_TYPE VARCHAR2(30),
PRODUCT_THICKNESS VARCHAR2(10),
HSN_CODE VARCHAR2(10) NOT NULL,
GST VARCHAR2(15) NOT NULL,
PRODUCT_UNIT VARCHAR2(10) DEFAULT 'SQFT',
PRODUCT_RATE NUMBER(10,2),
STATUS VARCHAR2(10) DEFAULT 'ACTIVE',
CREATED_AT DATE DEFAULT SYSDATE,
UPDATED_AT DATE,
DELETED_AT DATE  );

CREATE SEQUENCE PRODUCT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER PRODUCT_BI
    BEFORE INSERT ON PRODUCT
    FOR EACH ROW
    BEGIN
    :NEW.PRODUCT_ID:='JMJPPID'||LPAD(PRODUCT_SEQ.NEXTVAL,3,'0');
    END;
    /

// PURCHASE TABLE//

 CREATE TABLE PURCHASE(
      PURCHASE_ID VARCHAR2(10) PRIMARY KEY,
      SUPPLIER_ID VARCHAR2(10) ,
      PURCHASE_DATE DATE DEFAULT SYSDATE,
      DUE_DATE DATE,
      PURCHASE_BILLNO VARCHAR2(15) NOT NULL,
      PRODUCT_ID VARCHAR2(10) NOT NULL,
      PRODUCT_NAME VARCHAR2(30) NOT NULL,
      PRODUCT_THICKNESS VARCHAR2(10),
      PRODUCT_RATE NUMBER(10,2) NOT NULL CHECK (PRODUCT_RATE > 0),
      TOTAL_QUANTITY NUMBER(10,2) NOT NULL CHECK (TOTAL_QUANTITY > 0),
      TOTAL_GST NUMBER(10,2),
      DISCOUNT NUMBER(10,2),
      NET_PURCHASE_RATE NUMBER(10,2) NOT NULL CHECK (NET_PURCHASE_RATE >= 0),
      PAID_AMOUNT NUMBER(10,2) DEFAULT 0 CHECK (PAID_AMOUNT >= 0),
      DUE_AMOUNT NUMBER(10,2) CHECK (DUE_AMOUNT >= 0),
      PAYMENT_MODE VARCHAR2(10),
      SUPPLIER_COMPANY_NAME VARCHAR2(40) NOT NULL,
      CREATED_AT DATE DEFAULT SYSDATE,
      UPDATED_AT DATE,
      DELETED_AT DATE  );

CREATE SEQUENCE PURCHASE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

 CREATE OR REPLACE TRIGGER PURCHASE_ID
    BEFORE INSERT ON PURCHASE
    FOR EACH ROW
    BEGIN
    :NEW.PURCHASE_ID:='PRID'||LPAD(PURCHASE_SEQ.NEXTVAL,6,'0');
    END;
    /


// STOCK TABLE//

CREATE TABLE STOCK(
    STOCK_ID VARCHAR2(10) PRIMARY KEY,
    PRODUCT_ID VARCHAR2(10) NOT NULL,
    PRODUCT_NAME VARCHAR2(30),
    PRODUCT_THICKNESS VARCHAR2(10),
    STOCK_IN NUMBER(10,2) DEFAULT 0,
    STOCK_OUT NUMBER(10,2) DEFAULT 0,
    AVAILABLE_QUANTITY NUMBER(10,2) DEFAULT 0,
    MIN_STOCK_LEVEL NUMBER(10,2) DEFAULT 0,
    LAST_UPDATED DATE DEFAULT SYSDATE,
    CONSTRAINT FK_STOCK_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);


CREATE SEQUENCE STOCK_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER STOCK_BI
BEFORE INSERT ON STOCK
FOR EACH ROW
BEGIN
    :NEW.STOCK_ID := 'STID' || LPAD(STOCK_SEQ.NEXTVAL,6,'0');
    :NEW.LAST_UPDATED := SYSDATE;
END;
/


CREATE OR REPLACE TRIGGER STOCK_AFTER_PURCHASE
AFTER INSERT ON PURCHASE
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN

    SELECT COUNT(*) INTO v_count
    FROM STOCK
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;

    IF v_count = 0 THEN

        INSERT INTO STOCK(
            PRODUCT_ID,
            PRODUCT_NAME,
            PRODUCT_THICKNESS,
            STOCK_IN,
            AVAILABLE_QUANTITY,
            MIN_STOCK_LEVEL
        )
        VALUES(
            :NEW.PRODUCT_ID,
            :NEW.PRODUCT_NAME,
            :NEW.PRODUCT_THICKNESS,
            :NEW.TOTAL_QUANTITY,
            :NEW.TOTAL_QUANTITY,
            10
        );

    ELSE

        UPDATE STOCK
        SET STOCK_IN = STOCK_IN + :NEW.TOTAL_QUANTITY,
            AVAILABLE_QUANTITY = AVAILABLE_QUANTITY + :NEW.TOTAL_QUANTITY,
            LAST_UPDATED = SYSDATE
        WHERE PRODUCT_ID = :NEW.PRODUCT_ID;

    END IF;

END;
/

// FOR SELL//

 CREATE TABLE SELL(
  2      ORDER_ID VARCHAR2(10) PRIMARY KEY,
  3      ORDER_DATE DATE DEFAULT SYSDATE,
  4      CUSTOMER_NAME VARCHAR2(30) NOT NULL,
  5      CUSTOMER_ADDRESS VARCHAR2(50),
  6      CUSTOMER_PHONE VARCHAR2(15),
  7      PRODUCT_ID VARCHAR2(10) NOT NULL,
  8      PRODUCT_NAME VARCHAR2(30),
  9      PRODUCT_THICKNESS VARCHAR2(10),
 10      PRODUCT_QUANTITY NUMBER(10,2) NOT NULL,
 11      PRODUCT_RATE NUMBER(10,2) NOT NULL,
 12      GST NUMBER(5,2) DEFAULT 0,
 13      PAID_AMOUNT NUMBER(10,2) DEFAULT 0,
 14      DUE_AMOUNT NUMBER(10,2) DEFAULT 0,
 15      GRAND_TOTAL NUMBER(10,2) DEFAULT 0,
 16      PAYMENT_MODE VARCHAR2(20),
 17      CONSTRAINT FK_SELL_PRODUCT FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
 18      CONSTRAINT UQ_SELL_ORDER UNIQUE(CUSTOMER_NAME, ORDER_DATE, PRODUCT_ID)
 19  );


CREATE SEQUENCE SELL_SEQ
  2  START WITH 1
  3  INCREMENT BY 1
  4  NOCACHE
  5  NOCYCLE;


CREATE OR REPLACE TRIGGER SELL_BI
    BEFORE INSERT ON SELL
    FOR EACH ROW
    BEGIN
        :NEW.ORDER_ID := 'ORID' || LPAD(SELL_SEQ.NEXTVAL,6,'0');
    END;
    /

 CREATE OR REPLACE TRIGGER STOCK_AFTER_SELL
  2  AFTER INSERT ON SELL
  3  FOR EACH ROW
  4  BEGIN
  5      UPDATE STOCK
  6      SET STOCK_OUT = STOCK_OUT + :NEW.PRODUCT_QUANTITY,
  7          AVAILABLE_QUANTITY = AVAILABLE_QUANTITY - :NEW.PRODUCT_QUANTITY,
  8          LAST_UPDATED = SYSDATE
  9      WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
 10  END;
 11  /

// EMPLOYEE//


CREATE TABLE EMPLOYEE
  2  (
  3  EMPLOYEE_ID VARCHAR2(10) PRIMARY KEY,
  4  EMPLOYEE_NAME VARCHAR2(30) NOT NULL,
  5  PHONE_NO VARCHAR2(15),
  6  ADDRESS VARCHAR2(50),
  7  JOINING_DATE DATE DEFAULT SYSDATE,
  8  SALARY NUMBER(10,2),
  9  PAYMENT_TYPE VARCHAR2(10),
 10  STATUS VARCHAR2(10)DEFAULT 'ACTIVE'
 11  );

CREATE SEQUENCE employee_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


 CREATE OR REPLACE TRIGGER EMPLOYEE_BI
  2  BEFORE INSERT ON EMPLOYEE
  3  FOR EACH ROW
  4  BEGIN
  5      :NEW.EMPLOYEE_ID := 'EMPID' || LPAD(EMPLOYEE_SEQ.NEXTVAL,5,'0');
  6  END;
  7  /


//ACCOUNT//

 CREATE TABLE ACCOUNT(
     ACCOUNT_ID VARCHAR2(10)PRIMARY KEY,
     REFERENCE_ID VARCHAR2(10),
     TRANSACTION_DATE DATE DEFAULT SYSDATE,
    CONTACT_NO VARCHAR2(15),
    PARTY_NAME VARCHAR2(50)NOT NULL,
    PARTY_TYPE VARCHAR2(15)CHECK(PARTY_TYPE IN('CUSTOMER','SUPPLIER','EMPLOYEE')),
    TRANSACTION_TYPE VARCHAR2(15),
    CASHFLOW_TYPE VARCHAR2(10)CHECK(CASHFLOW_TYPE IN('IN','OUT')),
    PAYMENT_MODE VARCHAR2(15)CHECK(PAYMENT_MODE IN('CASH','BANK','UPI')),
   GST_AMOUNT NUMBER(10,2),
   GSTIN VARCHAR2(15),
   NET_AMOUNT NUMBER(10,2)NOT NULL CHECK(NET_AMOUNT>=0),
   PAID_AMOUNT NUMBER(10,2)DEFAULT 0 CHECK(PAID_AMOUNT>=0),
   PENDING_AMOUNT NUMBER(10,2)DEFAULT 0 CHECK(PENDING_AMOUNT>=0),
   PAYMENT_STATUS VARCHAR2(15)CHECK(PAYMENT_STATUS IN('PAID','PENDING','PARTIAL')),
   DUE_DATE DATE,
   CREATED_AT DATE DEFAULT SYSDATE,
   UPDATED_AT DATE
   );

 CREATE SEQUENCE ACCOUNT_SEQ
    START WITH 1
        INCREMENT BY 1
        NOCACHE
        NOCYCLE;

 CREATE OR REPLACE TRIGGER ACCOUNT_BI
    BEFORE INSERT ON ACCOUNT
    FOR EACH ROW
    BEGIN
        IF :NEW.ACCOUNT_ID IS NULL THEN
            :NEW.ACCOUNT_ID := 'ACID' || LPAD(ACCOUNT_SEQ.NEXTVAL, 6, '0');
        END IF;
    END;
    /

CREATE OR REPLACE TRIGGER trg_purchase_account
AFTER INSERT ON PURCHASE
FOR EACH ROW
BEGIN
    INSERT INTO ACCOUNT(
        TRANSACTION_DATE, PARTY_NAME, PARTY_TYPE,
        TRANSACTION_TYPE, CASHFLOW_TYPE, PAYMENT_MODE,
        GST_AMOUNT, NET_AMOUNT, PAID_AMOUNT, PENDING_AMOUNT,
        PAYMENT_STATUS, DUE_DATE, REFERENCE_ID
    )
    VALUES(
        :NEW.PURCHASE_DATE,
        :NEW.SUPPLIER_COMPANY_NAME,
        'SUPPLIER',
        'PURCHASE',
        'OUT',
        :NEW.PAYMENT_MODE,
        :NEW.TOTAL_GST,
        :NEW.NET_PURCHASE_RATE,
        :NEW.PAID_AMOUNT,
        :NEW.DUE_AMOUNT,
        CASE 
            WHEN :NEW.DUE_AMOUNT=0 THEN 'PAID'
            WHEN :NEW.PAID_AMOUNT=0 THEN 'PENDING'
            ELSE 'PARTIAL'
        END,
        :NEW.DUE_DATE,
        :NEW.PURCHASE_ID  -- use PURCHASE_ID as reference
    );
END;
/

CREATE OR REPLACE TRIGGER trg_sales_account
AFTER INSERT ON SELL
FOR EACH ROW
BEGIN
    INSERT INTO ACCOUNT(
        TRANSACTION_DATE, CONTACT_NO, PARTY_NAME, PARTY_TYPE,
        TRANSACTION_TYPE, CASHFLOW_TYPE, PAYMENT_MODE,
        GST_AMOUNT, NET_AMOUNT, PAID_AMOUNT, PENDING_AMOUNT,
        PAYMENT_STATUS, DUE_DATE, REFERENCE_ID
    )
    VALUES(
        NVL(:NEW.ORDER_DATE, SYSDATE),
        NVL(:NEW.CUSTOMER_PHONE, 'NA'),
        NVL(:NEW.CUSTOMER_NAME, 'UNKNOWN'),
        'CUSTOMER',
        'SELL',
        'IN',
        CASE 
            WHEN UPPER(:NEW.PAYMENT_MODE) IN ('CASH','BANK','UPI')
                THEN UPPER(:NEW.PAYMENT_MODE)
            ELSE 'CASH'
        END,
        NVL(:NEW.GST, 0),
        NVL(:NEW.GRAND_TOTAL, 0),
        NVL(:NEW.PAID_AMOUNT, 0),
        NVL(:NEW.DUE_AMOUNT, 0),
        CASE 
            WHEN NVL(:NEW.DUE_AMOUNT,0) = 0 THEN 'PAID'
            WHEN NVL(:NEW.PAID_AMOUNT,0) = 0 THEN 'PENDING'
            ELSE 'PARTIAL'
        END,
        NULL,
        :NEW.ORDER_ID  -- use ORDER_ID as reference
    );
END;
/

CREATE OR REPLACE TRIGGER trg_employee_account
AFTER INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
INSERT INTO ACCOUNT(
TRANSACTION_DATE, CONTACT_NO, PARTY_NAME, PARTY_TYPE,
TRANSACTION_TYPE, CASHFLOW_TYPE, PAYMENT_MODE,
GST_AMOUNT, NET_AMOUNT, PAID_AMOUNT, PENDING_AMOUNT,
PAYMENT_STATUS, DUE_DATE, REFERENCE_ID
)
VALUES(
:NEW.JOINING_DATE,
:NEW.PHONE_NO,
:NEW.EMPLOYEE_NAME,
'EMPLOYEE',
'SALARY',
'OUT',
'CASH',
NULL,
:NEW.SALARY,
:NEW.SALARY,
0,
'PAID',
NULL,
:NEW.EMPLOYEE_ID   
);
END;
/

 CREATE OR REPLACE TRIGGER trg_purchase_update
    AFTER UPDATE ON PURCHASE
    FOR EACH ROW
    BEGIN
    UPDATE ACCOUNT
SET
    TRANSACTION_DATE = :NEW.PURCHASE_DATE,
    PARTY_NAME       = :NEW.SUPPLIER_COMPANY_NAME,
    PAYMENT_MODE     = :NEW.PAYMENT_MODE,
    GST_AMOUNT       = :NEW.TOTAL_GST,
    NET_AMOUNT       = :NEW.NET_PURCHASE_RATE,
    PAID_AMOUNT      = :NEW.PAID_AMOUNT,
    PENDING_AMOUNT   = :NEW.DUE_AMOUNT,
    PAYMENT_STATUS   =
        CASE
            WHEN :NEW.DUE_AMOUNT = 0 THEN 'PAID'
            WHEN :NEW.PAID_AMOUNT = 0 THEN 'PENDING'
            ELSE 'PARTIAL'
        END,
    DUE_DATE = :NEW.DUE_DATE
WHERE REFERENCE_ID = :OLD.PURCHASE_ID;
END;
/
    


CREATE OR REPLACE TRIGGER trg_sell_update
  2  AFTER UPDATE ON SELL
  3  FOR EACH ROW
  4  BEGIN
  5      UPDATE ACCOUNT
  6      SET
  7          TRANSACTION_DATE = NVL(:NEW.ORDER_DATE, SYSDATE),
  8          CONTACT_NO       = NVL(:NEW.CUSTOMER_PHONE, 'NA'),
  9          PARTY_NAME       = NVL(:NEW.CUSTOMER_NAME, 'UNKNOWN'),
 10          PAYMENT_MODE     = CASE
 11                                 WHEN UPPER(:NEW.PAYMENT_MODE) IN ('CASH','BANK','UPI')
 12                                 THEN UPPER(:NEW.PAYMENT_MODE)
 13                                 ELSE 'CASH'
 14                             END,
 15          GST_AMOUNT       = NVL(:NEW.GST, 0),
 16          NET_AMOUNT       = NVL(:NEW.GRAND_TOTAL, 0),
 17          PAID_AMOUNT      = NVL(:NEW.PAID_AMOUNT, 0),
 18          PENDING_AMOUNT   = NVL(:NEW.DUE_AMOUNT, 0),
 19          PAYMENT_STATUS   = CASE
 20                                 WHEN NVL(:NEW.DUE_AMOUNT,0) = 0 THEN 'PAID'
 21                                 WHEN NVL(:NEW.PAID_AMOUNT,0) = 0 THEN 'PENDING'
 22                                 ELSE 'PARTIAL'
 23                             END,
 24          UPDATED_AT       = SYSDATE
 25      WHERE TRIM(REFERENCE_ID) = TRIM(:NEW.ORDER_ID);  -- SAFELY MATCH REFERENCE
 26  END;
 27  /

   
CREATE OR REPLACE TRIGGER trg_employee_update
AFTER UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
UPDATE ACCOUNT
SET
    PARTY_NAME     = :NEW.EMPLOYEE_NAME,
    CONTACT_NO     = :NEW.PHONE_NO,
    NET_AMOUNT     = :NEW.SALARY,
    PAID_AMOUNT    = :NEW.SALARY,
    PENDING_AMOUNT = 0,
    PAYMENT_STATUS = 'PAID',
    UPDATED_AT     = SYSDATE
WHERE
    REFERENCE_ID = :OLD.EMPLOYEE_ID;  
END;
/



//supplier//
 CREATE TABLE SUPPLIER (
        SUPPLIER_ID VARCHAR2(10) PRIMARY KEY,
        SUPPLIER_COMPANY_NAME VARCHAR2(50) NOT NULL,
        PHONE VARCHAR2(15),
        ADDRESS VARCHAR2(100),
        GST_NO VARCHAR2(20),
        ACCOUNT_NO VARCHAR2(30),
        STATUS VARCHAR2(10) DEFAULT 'ACTIVE'
    );

 CREATE SEQUENCE SEQ_SUPPLIER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

 CREATE OR REPLACE TRIGGER TRG_SUPPLIER_ID
    BEFORE INSERT ON SUPPLIER
    FOR EACH ROW
    BEGIN
        IF :NEW.SUPPLIER_ID IS NULL THEN
            :NEW.SUPPLIER_ID := 'SUPID' || LPAD(SEQ_SUPPLIER.NEXTVAL, 5, '0');
        END IF;
    END;
    /












